import Header from 'components/Header';
import Sidebar from 'components/molecules/Sidebar';

export const metadata = {
    title: 'Marquee Prototype Vercel - Dashboard',
    description: 'Generated by create next app',
};

export default function DashboardLayout({ children }) {
    return (
        <main className={`page--marquee-dashboard`}>
            <Sidebar />
            <div className='marquee-dashboard flex-grow'>
                <Header />
                {children}
            </div>
        </main>
    );
}
